config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "kittens#index"
  resources :kittens
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :softness, numericality: { greater_than: 0, less_than: 6 }
  validates :cuteness, numericality: { greater_than: 0, less_than: 6 }

  def to_s
    "Name: #{name}\nAge: #{age}\nCuteness #{cuteness}\nSoftness: #{softness}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to @kitten, notice: "Kitten successfully created"
    else
      flash.now[:alert] = "Hey Buddy need a ride? I was just on my way to the big Doofus Convention!"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: "Kitten successfully updated"
    else
      flash.now[:alert] = "Hey Buddy need a ride? I was just on my way to the big Doofus Convention!"
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to root_path, status: :see_other, notice: "Kitten successfully deleted"
  end

  private
  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: kitten do |form| %>
  <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :cuteness %>
    <%= form.number_field :cuteness %>
    <% kitten.errors.full_messages_for(:cuteness).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :softness %>
    <%= form.number_field :softness %>
    <% kitten.errors.full_messages_for(:softness).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <%= form.submit %>
<% end %>

app/views/kittens/edit.html.erb
<h2>Edit kitten</h2>
<%= link_to 'Delete Kitten', kitten_path(@kitten), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %><br>
<%= render 'kittens/form', kitten: @kitten %>

app/views/kittens/index.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
<h2>Kittens Home page</h2>
<%= link_to 'Create a Kitten', new_kitten_path %>
<ul>
  <% @kittens.each do |kitten|%>
    <li>
      <%= link_to kitten.name, kitten %> |
      <%= link_to 'Delete Kitten', kitten_path(kitten), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %><br>
    </li>
  <% end %>
</ul>
  

app/views/kittens/new.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
<h2>Create a Kitten</h2>
<%= link_to 'Home Page', kittens_path %>
<%= render "kittens/form", kitten: @kitten %>

app/views/kittens/show.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
<h2>Kitten Profile</h2>
<%= link_to 'Home Page', kittens_path  %><br>
<%= link_to 'Edit Kitten', edit_kitten_path %><br>
<%= link_to 'Delete Kitten', kitten_path(@kitten), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %><br>
<%= @kitten %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Kittens Odin" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>